name: maz2
channels:
  - defaults
  - pytorch
  - pyg
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.9.1
  - cudatoolkit=11.3
  - scipy
  - matplotlib
  - ipykernel
  - pyg
  - pyglet
  - tensorboard
  - optuna
  - plotly
  - joblib
  - absl-py

